apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1wok
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1wok
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1wok
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1wok
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1wok
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jnsj-tenant/rhtap-demo-app/hacbs-test-project-1wok@sha256:3eb0479fcf471f4919ac29c865d88465dfda69ac15ff47fdeebb5d55c78df05a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
