apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1wok
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jnsj-tenant/rhtap-demo-app/hacbs-test-project-1wok@sha256:3eb0479fcf471f4919ac29c865d88465dfda69ac15ff47fdeebb5d55c78df05a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
